apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fleet-demo
spec:
  ingressClassName: traefik
  rules:
    - host: fleet-demo.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fleet-demo
                port:
                  number: 80
